# Generated by Django 3.1.1 on 2020-09-15 07:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('province', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.person')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Customer',
            },
            bases=('dashboard.person',),
        ),
    ]
