# Generated by Django 3.1.1 on 2020-09-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=30)),
                ('size', models.FloatField()),
                ('price', models.FloatField()),
                ('no_stocks', models.IntegerField()),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
