# Generated by Django 3.1.1 on 2020-10-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phoneNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
