# Generated by Django 3.1.1 on 2020-10-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
    ]
