# Generated by Django 3.1.1 on 2020-10-08 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201005_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_registered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
