# Generated by Django 3.1.1 on 2020-10-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_product_date_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
