# Generated by Django 3.1.1 on 2020-10-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20201009_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='isDeleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='isDeleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='isDeleted',
            field=models.IntegerField(default=0),
        ),
    ]
